# Generated by Django 5.0.6 on 2024-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='bpQpMRpSHsse9UkB9QBUVx', max_length=50, unique=True),
        ),
    ]
