# Generated by Django 5.0.6 on 2024-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='ho3eHhUjH8PjpwRdfBUa7m', max_length=50),
        ),
    ]
