# Generated by Django 5.0.6 on 2024-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='DtFw9Hy6WopeiZLSN6ZppD', max_length=50),
        ),
    ]
