# Generated by Django 5.0.6 on 2024-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='9DsbzNdQ5o3x3yV36WHU4k', max_length=50, unique=True),
        ),
    ]
