# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_avatar_alter_profile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='NtHpeti6LtBgyokCjdJFvu', max_length=50),
        ),
    ]
