# Generated by Django 5.0.6 on 2024-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='a7JMaZRK5sPyRiktXMGYQA', max_length=50, unique=True),
        ),
    ]
