# Generated by Django 5.0.6 on 2024-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='a3oe53xE6myw394iJn7sXE', max_length=50, unique=True),
        ),
    ]
