# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_phone_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='BoPMiD7vyXAzXjr6kintQR', max_length=50),
        ),
    ]
