# Generated by Django 5.0.6 on 2024-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='f9Ci9qz4BCdofV9jDdSaEu', max_length=50),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
