# Generated by Django 5.0.6 on 2024-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_options_alter_profile_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='KUwWwooizAKG2kCnroudwi', max_length=50),
        ),
    ]
