# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='JciDXHJWyurrMQsbmWLYFQ', max_length=50),
        ),
    ]
