# Generated by Django 5.0.6 on 2024-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='ayG4U6rtwVcu62Qekfptad', max_length=50),
        ),
    ]
