# Generated by Django 5.0.6 on 2024-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='M7wUB4scmnEy4vQQw3v4Wx', max_length=50),
        ),
    ]
