# Generated by Django 5.0.6 on 2024-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='DeNnEPybCXtp9JT9UHc4er', max_length=50),
        ),
    ]
