# Generated by Django 5.0.6 on 2024-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='2MWjC9cKUfP6QDfj3JQbyh', max_length=50, unique=True),
        ),
    ]
