# Generated by Django 5.0.6 on 2024-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_profile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='o32KWMJpTDGNPrtXBFcX23', max_length=50, unique=True),
        ),
    ]
