# Generated by Django 5.0.6 on 2024-06-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_public_id'),
        ('supports', '0002_comment_public_id_report_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='G9SYyufxFewWopXYKniVgq', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='news', to='supports.tag'),
        ),
    ]
