# Generated by Django 5.0.6 on 2024-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content_alter_news_likes_and_more'),
        ('supports', '0003_alter_comment_public_id_alter_report_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='3bZz8RFQQDcWjEzky4H3Pt', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='supports.tag'),
        ),
    ]
