# Generated by Django 5.0.6 on 2024-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_public_id_alter_news_tags'),
        ('supports', '0004_alter_comment_public_id_alter_report_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='a7JMaZRK5sPyRiktXMGYQA', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='supports.tag'),
        ),
    ]
