# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_alter_news_likes_alter_news_media_and_more'),
        ('supports', '0004_alter_comment_public_id_alter_report_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='R3p5bi92bAPx62JUhKQ6Db', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='supports.tag'),
        ),
    ]
