# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_likes_alter_news_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='FNdKETPSuc3LaCwxfk3nLX', max_length=50),
        ),
    ]
