# Generated by Django 5.0.6 on 2024-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_public_id_alter_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='a3oe53xE6myw394iJn7sXE', max_length=50, unique=True),
        ),
    ]
