# Generated by Django 5.0.6 on 2024-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='YBjQyai7a5XCfXh3rm6qdp', max_length=50),
        ),
    ]
