# Generated by Django 5.0.6 on 2024-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='Cj5cNcvM9uEX5fSZGHV6bj', max_length=50),
        ),
    ]
