# Generated by Django 5.0.6 on 2024-07-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_remove_channel_collaborators_alter_channel_public_id_and_more'),
        ('news', '0012_alter_news_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='3rJymZdVB6evsfKZvrJ88q', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_news', to='channel.publisher'),
        ),
    ]
