# Generated by Django 5.0.6 on 2024-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_public_id_alter_news_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='WzLode2RFfjjvFPfhpo32T', max_length=50),
        ),
    ]
