# Generated by Django 5.0.6 on 2024-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_news_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='eS5nxy3SvQFYEe9AkjsoCm', max_length=50, unique=True),
        ),
    ]
