# Generated by Django 5.0.6 on 2024-07-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channel_public_id_alter_publisher_public_id'),
        ('post', '0004_alter_news_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to='channel.publisher'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_id',
            field=models.CharField(default='FSjNcrTg5DKCm5fKBTVh2m', max_length=50, unique=True),
        ),
    ]
