# Generated by Django 5.1 on 2024-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_channel_public_id_alter_publisher_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='follows',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='iLkwEki4NXAZ93D74DoM6J', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='iLkwEki4NXAZ93D74DoM6J', max_length=50),
        ),
    ]
