# Generated by Django 5.0.6 on 2024-07-10 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('stream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='ALKey6YRJETJXT6Ur4s2XN', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='ALKey6YRJETJXT6Ur4s2XN', max_length=50, unique=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('dep_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='supports.comment')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stream.stream')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='ALKey6YRJETJXT6Ur4s2XN', max_length=50, unique=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='news.news')),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='stream.stream')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
