# Generated by Django 5.0.6 on 2024-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='UaPVejooYc88G2kCtdxsGa', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='SJTkmRVNURuMapCL32Y27j', max_length=50),
        ),
    ]
