# Generated by Django 5.0.6 on 2024-06-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_alter_news_likes_alter_news_media_and_more'),
        ('stream', '0003_stream_description_alter_stream_public_id_and_more'),
        ('supports', '0002_comment_public_id_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='4pKsQz8xMiiy7ELUgk7ZLC', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stream.stream'),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='NFyMCXgdoomLrRiZWmfAy5', max_length=50),
        ),
    ]
