# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='PCTymPkHJVzxFMdysYXPug', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='DKvmqh7hVMY4JWzoqiXahC', max_length=50),
        ),
    ]
