# Generated by Django 5.0.6 on 2024-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_alter_comment_public_id_alter_report_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='a3oe53xE6myw394iJn7sXE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='a3oe53xE6myw394iJn7sXE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='public_id',
            field=models.CharField(default='a3oe53xE6myw394iJn7sXE', max_length=50, unique=True),
        ),
    ]
