# Generated by Django 5.0.6 on 2024-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0007_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='3rMu7uwtfhcuqvxjkKUTdV', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='nkhG99VAuKnUG5bNustUUS', max_length=50),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
