# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0008_alter_comment_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='fTZMe2dgf62PCLr6nBBCDR', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='o8SYTrtuMzKRnXWtE5mJpA', max_length=50),
        ),
    ]
