# Generated by Django 5.0.6 on 2024-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0010_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='ZabZDcmzKkXUcFNekPS6Pv', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='kyCqYjdd3e6FFLqV7mm9Lj', max_length=50),
        ),
    ]
