# Generated by Django 5.0.6 on 2024-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0011_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='P5tgbTXcHyoxRsKkVSmeCZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='Fs7ZzbrPpD7xv3Np525cir', max_length=50),
        ),
    ]
