# Generated by Django 5.0.6 on 2024-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0012_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='Ezbdzv98SKMx8BFjteGWjn', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='MqYqSYVvtLExhiHbDK9EKN', max_length=50),
        ),
    ]
