# Generated by Django 5.0.6 on 2024-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0013_alter_comment_public_id_alter_report_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
    ]
