# Generated by Django 5.0.6 on 2024-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0016_alter_comment_public_id_alter_report_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
    ]
