# Generated by Django 5.0.6 on 2024-07-14 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='E8EivJ2TxpaxqNKwBsS8hz', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_stream', to=settings.AUTH_USER_MODEL)),
                ('streamers', models.ManyToManyField(related_name='my_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stream',
            },
        ),
    ]
