# Generated by Django 5.0.6 on 2024-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='c4i2CWGsK7HhWuKQ8rHR5y', max_length=50),
        ),
    ]
