# Generated by Django 5.0.6 on 2024-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='3bZz8RFQQDcWjEzky4H3Pt', max_length=50, unique=True),
        ),
    ]
