# Generated by Django 5.0.6 on 2024-06-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_stream_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='du7iUJ9mQZhpKaC3u5ain8', max_length=50),
        ),
        migrations.AlterField(
            model_name='stream',
            name='streamers',
            field=models.ManyToManyField(null=True, related_name='my_streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
