# Generated by Django 5.0.6 on 2024-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='FSjNcrTg5DKCm5fKBTVh2m', max_length=50, unique=True),
        ),
    ]
