# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_stream_description_alter_stream_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='PcbSJb2pKHzqmMkRgGVMyW', max_length=50),
        ),
        migrations.AlterField(
            model_name='stream',
            name='streamers',
            field=models.ManyToManyField(related_name='my_streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
