# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_stream_public_id_alter_stream_streamers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='UFip2zoTtwKHiX9xg2U7Jk', max_length=50),
        ),
    ]
