# Generated by Django 5.0.6 on 2024-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='8odJDgtana2xAYo2kSEspw', max_length=50),
        ),
    ]
