# Generated by Django 5.0.6 on 2024-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={},
        ),
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='ZG3TMBcBq7hMRn6gSVhz2Y', max_length=50),
        ),
        migrations.AlterModelTable(
            name='stream',
            table='stream',
        ),
    ]
