# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_alter_stream_options_alter_stream_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='jtUCwJo6N4LNTZ7phmMMoV', max_length=50),
        ),
    ]
