# Generated by Django 5.0.6 on 2024-07-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='hnNz8VQEMJrNWiBxQ3AcVL', max_length=50),
        ),
    ]
