# Generated by Django 5.0.6 on 2024-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='att62onqFdeWDqCNMk7R9T', max_length=50),
        ),
    ]
