# Generated by Django 5.0.6 on 2024-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0012_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='hyugqBYrvrayPmaUzCQJCa', max_length=50),
        ),
    ]
