# Generated by Django 5.0.6 on 2024-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0013_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
    ]
