# Generated by Django 5.0.6 on 2024-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0016_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
    ]
