# Generated by Django 5.0.6 on 2024-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0018_alter_stream_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='public_id',
            field=models.CharField(default='kqDFkv9jNZ3CZgHjc3ySGv', max_length=50, unique=True),
        ),
    ]
