# Generated by Django 5.1 on 2024-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='DpMuC2jVXYnC94SSjnRmd8', max_length=50),
        ),
    ]
