# Generated by Django 5.1 on 2024-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='media',
        ),
        migrations.AlterField(
            model_name='comment',
            name='public_id',
            field=models.CharField(default='Nzk8d74ZFifGyEzioVuxJm', max_length=50),
        ),
    ]
