# Generated by Django 5.1 on 2024-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('folder', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=300)),
                ('public_id', models.CharField(max_length=300)),
                ('xyz', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'storage_manager',
            },
        ),
    ]
