# Generated by Django 5.1 on 2024-09-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemanager',
            name='xyz',
        ),
    ]
