# Generated by Django 5.1 on 2024-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='6xVyi7g3VpmaWNuA35LDsU', max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='6xVyi7g3VpmaWNuA35LDsU', max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('media', models.JSONField()),
                ('title', models.CharField(max_length=300)),
                ('likes', models.JSONField()),
                ('slug', models.CharField(max_length=300)),
                ('total_views', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='news.tag')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
    ]
