# Generated by Django 5.1 on 2024-09-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_id',
            field=models.CharField(default='njuuxV2TmzF2ZTLev6qvmF', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='news.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='public_id',
            field=models.CharField(default='njuuxV2TmzF2ZTLev6qvmF', max_length=50),
        ),
    ]
