# Generated by Django 5.1 on 2024-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_likes_alter_post_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='public_id',
            field=models.CharField(default='DpMuC2jVXYnC94SSjnRmd8', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='public_id',
            field=models.CharField(default='DpMuC2jVXYnC94SSjnRmd8', max_length=50),
        ),
    ]
