# Generated by Django 5.0.6 on 2024-07-14 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='UUVmzqLjyrWAysyf2veGQw', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_channels', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(default='UUVmzqLjyrWAysyf2veGQw', max_length=50, unique=True)),
                ('is_channel_admin', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_publisher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
    ]
