# Generated by Django 5.0.6 on 2024-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='CtwkMgJLscQWw8XB8KJKpv', max_length=50),
        ),
    ]
