# Generated by Django 5.0.6 on 2024-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='6Rtm3BzHAL46crwVm5J5AP', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='6Rtm3BzHAL46crwVm5J5AP', max_length=50, unique=True),
        ),
    ]
