# Generated by Django 5.0.6 on 2024-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_public_id_alter_publisher_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='9DsbzNdQ5o3x3yV36WHU4k', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='9DsbzNdQ5o3x3yV36WHU4k', max_length=50, unique=True),
        ),
    ]
