# Generated by Django 5.0.6 on 2024-06-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='collaborators',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='QXKPN7hy2XqNQADEyySFbg', max_length=50),
        ),
    ]
