# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_avatar_alter_channel_collaborators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(related_name='followed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='nukFFNxBfs43KR9S8Xp5yu', max_length=50),
        ),
    ]
