# Generated by Django 5.0.6 on 2024-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_public_id_alter_publisher_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='a7JMaZRK5sPyRiktXMGYQA', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='a7JMaZRK5sPyRiktXMGYQA', max_length=50, unique=True),
        ),
    ]
