# Generated by Django 5.0.6 on 2024-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_is_verified_alter_channel_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='FSjNcrTg5DKCm5fKBTVh2m', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='FSjNcrTg5DKCm5fKBTVh2m', max_length=50, unique=True),
        ),
    ]
