# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_alter_channel_followers_alter_channel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='YUig6m26Fxw43ginivS6Vd', max_length=50),
        ),
    ]
