# Generated by Django 5.0.6 on 2024-06-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_channel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='K9c8iTDMJyH4EcqdrQMBUy', max_length=50),
        ),
    ]
