# Generated by Django 5.0.6 on 2024-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_alter_channel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='A9jUUHhQVrUebHJobq4vjb', max_length=50),
        ),
    ]
