# Generated by Django 5.0.6 on 2024-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_channel_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='kQ5Kbv4SYNzLoEbdyTsxXw', max_length=50),
        ),
    ]
