# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_channel_options_alter_channel_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='collaborators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='AKuRvuc4aADUhWfiQsyia7', max_length=50),
        ),
    ]
