# Generated by Django 5.0.6 on 2024-06-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_alter_channel_avatar_alter_channel_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='XDCcKxQdL2LLpH7Z5ZBnh5', max_length=50),
        ),
    ]
