# Generated by Django 5.0.6 on 2024-07-02 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_alter_channel_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='E5P34DJinjfs96J4MKMNbu', max_length=50),
        ),
    ]
