# Generated by Django 5.0.6 on 2024-07-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_alter_channel_followers_alter_channel_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='collaborators',
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='YYbU5NjovKYjS5v9drwAJy', max_length=50),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=True)),
                ('public_id', models.CharField(default='ib3y2Fzvk8qT4zwKnBCVWs', max_length=50)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publishers',
            },
        ),
    ]
