# Generated by Django 5.0.6 on 2024-07-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_remove_channel_collaborators_alter_channel_public_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='FMKByhBnnoHZDwyEERVyEe', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='oBorNi3RcYuDxfQz82goK8', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
