# Generated by Django 5.0.6 on 2024-07-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_alter_channel_public_id_alter_publisher_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='UGeQzypyQxwkgdtBxmKPug', max_length=50, unique=True),
        ),
    ]
