# Generated by Django 5.0.6 on 2024-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_alter_channel_public_id_alter_publisher_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='is_admin',
            new_name='is_channel_admin',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='is_member',
        ),
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='eS5nxy3SvQFYEe9AkjsoCm', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='eS5nxy3SvQFYEe9AkjsoCm', max_length=50, unique=True),
        ),
    ]
