# Generated by Django 5.0.6 on 2024-07-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0016_rename_is_admin_publisher_is_channel_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='channel.channel'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='public_id',
            field=models.CharField(default='cuTa4PUVJ4k8boMyQxrU5Q', max_length=50, unique=True),
        ),
    ]
