# Generated by Django 5.1 on 2024-08-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_id',
            field=models.CharField(default='6EZDuwMWNwHJp6EsqHoNfP', max_length=40),
        ),
    ]
